package lt.vu.usecases.mybatis.model;

public class Flight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FLIGHT.ID
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FLIGHT.DEPART
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    private String depart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FLIGHT.ARRIVE
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    private String arrive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FLIGHT.PLANE_ID
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    private Integer planeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FLIGHT.ID
     *
     * @return the value of PUBLIC.FLIGHT.ID
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FLIGHT.ID
     *
     * @param id the value for PUBLIC.FLIGHT.ID
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FLIGHT.DEPART
     *
     * @return the value of PUBLIC.FLIGHT.DEPART
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    public String getDepart() {
        return depart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FLIGHT.DEPART
     *
     * @param depart the value for PUBLIC.FLIGHT.DEPART
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    public void setDepart(String depart) {
        this.depart = depart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FLIGHT.ARRIVE
     *
     * @return the value of PUBLIC.FLIGHT.ARRIVE
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    public String getArrive() {
        return arrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FLIGHT.ARRIVE
     *
     * @param arrive the value for PUBLIC.FLIGHT.ARRIVE
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    public void setArrive(String arrive) {
        this.arrive = arrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FLIGHT.PLANE_ID
     *
     * @return the value of PUBLIC.FLIGHT.PLANE_ID
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    public Integer getPlaneId() {
        return planeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FLIGHT.PLANE_ID
     *
     * @param planeId the value for PUBLIC.FLIGHT.PLANE_ID
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    public void setPlaneId(Integer planeId) {
        this.planeId = planeId;
    }
}