package lt.vu.usecases.mybatis.dao;

import lt.vu.usecases.mybatis.model.Plane;

import java.util.List;

public interface PlaneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    int insert(Plane record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    Plane selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    List<Plane> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue May 02 01:21:14 EEST 2017
     */
    int updateByPrimaryKey(Plane record);
}